scrape_configs:
  - job_name: node
    scrape_interval: 5s
    static_configs:
    - targets: ['node-exporter:9100']

  - job_name: mysql
    scrape_interval: 5s
    static_configs:
    - targets: ['mysql-exporter:9104']